<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_password</name>
   <tag></tag>
   <elementGuidId>02ceded9-2839-4dcc-b684-44480e0a241d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_75c0b9dc-bd11-4026-9c02-df339169eaee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'password')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a73cde1-22bf-4d10-bb54-ca5e98fbe595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>542a191a-9d57-45f3-bc5d-edcc3fe2b497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>81b82b15-27a4-43df-b797-b6bc75dfa002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9080372c-d666-4feb-b9cb-9789411a086b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f679460b-bb95-416a-b791-015fdd974ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_75c0b9dc-bd11-4026-9c02-df339169eaee</value>
      <webElementGuid>cb4f957d-e989-48b7-b8cd-3c4b9de0ad23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9b741339-13bb-4a2d-b1b6-3e2933f4bdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>335b2ee9-c99e-4db2-a541-48ab2192089f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_75c0b9dc-bd11-4026-9c02-df339169eaee&quot;)</value>
      <webElementGuid>ccd6121a-ed8a-4230-8164-286865107234</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_75c0b9dc-bd11-4026-9c02-df339169eaee']</value>
      <webElementGuid>25571db7-611d-4abf-8667-18ec19a5c18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/form/div[2]/label/div/div/div[2]/input</value>
      <webElementGuid>58657ca3-68ae-4026-a7bf-261106c3cd2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div/div/div[2]/input</value>
      <webElementGuid>e36f91f5-34a8-46b3-a797-c595eb6778f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @id = 'f_75c0b9dc-bd11-4026-9c02-df339169eaee' and @type = 'password']</value>
      <webElementGuid>5c711bbe-2e95-460b-9bcb-d08d504d2495</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
