<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code</name>
   <tag></tag>
   <elementGuidId>0e62ff6b-ff1d-4566-8f31-84bbdad1cd51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0b527f0-bb7a-4ec7-9169-e1e9e553d1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>221358ef-d0c8-4bce-9929-42984420534a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Code</value>
      <webElementGuid>88fd8646-93c2-48d9-8d19-be88a726c9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f</value>
      <webElementGuid>b452ab0a-059e-498d-b0b5-56a7f821bfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a80e654-8d83-4962-9846-7b76e4cbe9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>ed4fb631-c90c-4a4d-8fc4-b0dbf1f1a534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f&quot;)</value>
      <webElementGuid>d1555a17-dbe8-48b8-8f84-7786e533c232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f']</value>
      <webElementGuid>40b9e61d-24e1-4831-a09c-968a5fee6024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[2]/div[2]/div/div/label/div/div/div[2]/input</value>
      <webElementGuid>fb76cf64-a66a-4332-a5b2-df29f296ae38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>de0ca0f3-6ba5-4fc9-9a10-81cf867d66fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Code' and @id = 'f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f' and @type = 'text']</value>
      <webElementGuid>4b4fd294-d4b9-4bce-a6a3-fc16bd3f3f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
