<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>4bf3942a-4f9e-4a50-ad1a-c9de5e4fdd0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@aria-label,'Email')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcdba128-7fcf-4a79-9701-bc38540802b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1ada9b0f-f6b3-4813-9e60-edf0fe23d222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>d6031bf5-2ad9-4224-b81c-1b242f453a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>9dccbed1-c630-4d79-90b4-e447581172c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e6b00987-c923-46de-a14f-aa7a6394115e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f</value>
      <webElementGuid>e67baa2a-d488-4526-b036-bcff81771398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9d44cb2-8c1e-4c97-a0a0-cb0babbabe0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>6fb7cda0-aae0-45ee-ab76-24e99fea9119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f&quot;)</value>
      <webElementGuid>0d60a167-3db2-4d0e-aa61-217168db83ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f']</value>
      <webElementGuid>5b50f177-318c-4e9c-868e-10b726721a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/form/div/label/div/div/div[2]/input</value>
      <webElementGuid>f1be0cb1-3c19-486f-862d-cde876ca6cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3e156b87-710d-4e0f-8915-8797c0472d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f' and @type = 'text']</value>
      <webElementGuid>72fe21eb-09c4-42c0-ad8d-31739e17060e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
