<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer</name>
   <tag></tag>
   <elementGuidId>d676c486-3731-4ea4-ae50-10ce30ebffee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28a34c46-ff40-4c36-b876-07ebc841ad37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ea251642-845e-44c3-8f83-cc3e9c9aa0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a969becf-db81-4661-8ae8-b2066f90e99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>db3525be-b47d-4fc7-b421-29e5d7af25c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>af7952f5-8b21-403f-b35e-f6c135ee6c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5524656e-940d-41df-89e1-8f2ba956f191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>948723c6-2c04-4b9f-b31c-7868010dcca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>258aaecf-e7bb-4631-88da-39f1eec99ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      <webElementGuid>a95b441b-2379-458e-9f9e-01c303b59d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__input q-placeholder col q-field__input--padding</value>
      <webElementGuid>2c285a0f-bc1c-412d-b8a3-ab5d858c9b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_a6ee8b0a-7dde-4558-a4d5-92035df88206&quot;)</value>
      <webElementGuid>b2898fc2-1a89-44ec-bcd5-02a99831bb50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>8c0ee1e6-f0fe-41b0-9893-34606470607c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[2]/div[2]/div/div/div/label/div/div/div[2]/div/input</value>
      <webElementGuid>d4763ce5-e329-46c5-b6f9-3a9c7397a615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>32690e0f-cecf-4ce8-a7a9-530f6799d901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>e42dbaaa-a62d-469a-95c6-bde9fa3dd02a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
