<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_START_extension-iframe</name>
   <tag></tag>
   <elementGuidId>f673a2ec-f41c-4478-92a5-b19898a2a86e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#extension-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='extension-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>662fe6f6-dc6b-4e4d-9f5a-37c091e87574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>extension-iframe</value>
      <webElementGuid>d0d31e85-1ea9-4e74-9dd1-e249506be2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ncl-ext-1.testing.cenora.io?c=eyJjaWQiOiJuY2wiLCJjb25maWciOnsiY29sb3JzIjp7InByaW1hcnkiOiIjMUQxRDFEIiwic2Vjb25kYXJ5IjoiIzAwNzFhNiIsImFjY2VudCI6IiNGRjgzMDkiLCJkYXJrIjoiIzM3MzczNyIsInBvc2l0aXZlIjoiIzIxQkE0NSIsIm5lZ2F0aXZlIjoiI0MxMDAxNSIsImluZm8iOiIjMzFDQ0VDIiwid2FybmluZyI6IiNGMUMwMzcifX0sInNlY3Rpb25zIjoiY2FzaW5vIiwidG9rZW4iOiJleUpyYVdRaU9pSjVOMXBMV0VKbFhDOUhOMlp1Y1ZWamVtTTRNa3BXV2tSWVExSlVObHd2YTI5WVRGUmtXalJJZVhWd2RGRTlJaXdpWVd4bklqb2lVbE15TlRZaWZRLmV5SnpkV0lpT2lJMU1ESmlOalJoWmkwelkySXhMVFF4T0RrdFlUTTBOUzFqWWpGaFkyWmhOakV5TmpFaUxDSnBjM01pT2lKb2RIUndjenBjTDF3dlkyOW5ibWwwYnkxcFpIQXVkWE10WldGemRDMHhMbUZ0WVhwdmJtRjNjeTVqYjIxY0wzVnpMV1ZoYzNRdE1WOHdUM1JFUms0ME56TWlMQ0pwWkdWdWRHbDBlU0k2SW5KdmJHVXViR2x1YTNOOGNtOXNaUzVzYjJkcGJueHliMnhsTG1Ob1lXNW5aVjl3WVhOemQyOXlaSHh5YjJ4bExtUmhjMmhpYjJGeVpIeHliMnhsTG14dloybHVmSEp2YkdVdVkyaGhibWRsWDNCaGMzTjNiM0prZkhKdmJHVXViR2x1YTNNaUxDSmhkWFJvWDNScGJXVWlPakUyTmpZMk5EZzFNVEVzSW01cFkydHVZVzFsSWpvaVVtRmlaSGxPUTB3aUxDSmpkWE4wYjIwNlpHRjBZVjloWTJObGMzTWlPaUp1WTJ3aUxDSmpkWE4wYjIwNllXTmpiM1Z1ZEY5cFpDSTZJaklpTENKbGVIQWlPakUyTmpZMk9URTNNVEVzSW1saGRDSTZNVFkyTmpZME9EVXhNU3dpYW5ScElqb2laVGRoWVRJMk5HSXRNVGM0TkMwME5qbGxMVGsyTlRrdE5UZGlPREF3TXpVeVpEazNJaXdpWlcxaGFXd2lPaUp5WVdKa2VTdHVZMnhBWTJWdWIzSmhMbU52YlNJc0ltTjFjM1J2YlRwMGFYUnNaU0k2SWxKRlVGSkZVMFZPVkVGVVNWWkZJaXdpWTNWemRHOXRPbkp2YkdWeklqb2ljbTlzWlM1c2FXNXJjM3h5YjJ4bExteHZaMmx1ZkhKdmJHVXVZMmhoYm1kbFgzQmhjM04zYjNKa2ZISnZiR1V1WkdGemFHSnZZWEprZkhKdmJHVXViRzluYVc1OGNtOXNaUzVqYUdGdVoyVmZjR0Z6YzNkdmNtUjhjbTlzWlM1c2FXNXJjeUlzSW1WdFlXbHNYM1psY21sbWFXVmtJanAwY25WbExDSmpkWE4wYjIwNllYQndYM0psYzI5MWNtTmxjeUk2SW5KdmJHVXViR2x1YTNNc2NtOXNaUzVzYjJkcGJpeHliMnhsTG1Ob1lXNW5aVjl3WVhOemQyOXlaQ3h5YjJ4bExtUmhjMmhpYjJGeVpDeHliMnhsTG14dloybHVMSEp2YkdVdVkyaGhibWRsWDNCaGMzTjNiM0prTEhKdmJHVXViR2x1YTNNaUxDSndhRzl1WlY5dWRXMWlaWEpmZG1WeWFXWnBaV1FpT25SeWRXVXNJbU52WjI1cGRHODZkWE5sY201aGJXVWlPaUkxTURKaU5qUmhaaTB6WTJJeExUUXhPRGt0WVRNME5TMWpZakZoWTJaaE5qRXlOakVpTENKamRYTjBiMjA2Y0d4MVoybHVjeUk2SWlJc0ltZHBkbVZ1WDI1aGJXVWlPaUpTWVdKa2VTSXNJbU4xYzNSdmJUcG5jbTkxY0hNaU9pSm5jbTkxY0M1allXeHNYMk5sYm5SbGNqMUpSRkJmVGtOTVgweHBkbVZGZUhCbGNtbGxibU5sWDFWelpYSnpMRk5WVUZCUFVsUjhaM0p2ZFhBdVkyOXRjR0Z1ZVQxdVkyd2lMQ0p2Y21sbmFXNWZhblJwSWpvaU5tVTNaVEUzTVRrdE9UWmxOaTAwWXpJNUxUaGlZVEl0TlRKak5UQXhabU15T1Roaklpd2lZM1Z6ZEc5dE9tRmpZMlZ6YzE5eVpYTjBjbWxqZEdsdmJuTWlPaUp5YjJ4bExtRm5aVzUwTG1OaGMybHVieUlzSW1GMVpDSTZJamN5Wm5Sa2NYVTBiVzAxWW5JeFpHNXJaM05zTkhSdWEzSnhJaXdpWlhabGJuUmZhV1FpT2lKbE9EZGpOR05qWWkwd016RmtMVFE1WldJdFlUQXhOUzFtTTJZMk16TTBOR0prTldVaUxDSmpkWE4wYjIwNmFYTmZkSEpoZG1Wc1gyRm5aVzUwSWpvaU1DSXNJblJ2YTJWdVgzVnpaU0k2SW1sa0lpd2libUZ0WlNJNklsSmhZbVI1SWl3aWNHaHZibVZmYm5WdFltVnlJam9pS3pFeE1URXhNVEV4TVRFaUxDSm1ZVzFwYkhsZmJtRnRaU0k2SWtkMWRHbGxjbkpsZWlKOS5QS0YyXzR1alFXaWN0RzUxNER4MUh3azV6RzJyY3Q3TldTWHNrcDdZN1hmUjBETGk3TWRLREh2cE00a2ZJRU1JV3dzbWtBRFdDTFpOWWRLYWdia0pjWEZJQXp1OVl1dnp5QzdVeFpwM2JOcVMtNVpLbHNnVk9vZHZfQ01mNTZZb2U2d1g5ZE9yeEVvakVhdWEtb1MyRzU4MElWX0h1YXVpNG5OUWx3bjlBVnhtVmMyajhqSTJTNXZ1dnppRGdtZHdreWlWNkZHOFRHZDZxcV8ycHVidTg0WWhRclN5bDhVcmNyakJyWDFZZ3VnWWhSdjMybUJWNWhiOWpNUllUbzlnSVV2cFV6VTdfd3pGVWpHY2RQdG9sLTNka2M1RGVGMy1FTXZ4QjRzR0VtYUlITFIzOG5RcDJ1d0FnZWU2VjhKQnV2dEFNa2d0TFo2c2JmdUtFTGpCdkEifQ==</value>
      <webElementGuid>54beed39-b66c-47ae-863a-39335a8bbd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>00547af6-97d6-4e98-9b1d-479ba94cd512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1a614dc4-5a35-40c6-836d-cd9f9b5be610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;extension-iframe&quot;)</value>
      <webElementGuid>ad17067c-2958-4e73-b875-66efc63bb79d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='extension-iframe']</value>
      <webElementGuid>13e7fa31-2135-4fef-8ada-2ac45e532a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[3]/div/div/div/div/div/div/main/div/iframe</value>
      <webElementGuid>9f13cb48-384f-4ba0-aa2a-cd42671a5319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>20354b3b-9128-4bb7-9bf7-1115ff71cea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'extension-iframe' and @src = 'https://ncl-ext-1.testing.cenora.io?c=eyJjaWQiOiJuY2wiLCJjb25maWciOnsiY29sb3JzIjp7InByaW1hcnkiOiIjMUQxRDFEIiwic2Vjb25kYXJ5IjoiIzAwNzFhNiIsImFjY2VudCI6IiNGRjgzMDkiLCJkYXJrIjoiIzM3MzczNyIsInBvc2l0aXZlIjoiIzIxQkE0NSIsIm5lZ2F0aXZlIjoiI0MxMDAxNSIsImluZm8iOiIjMzFDQ0VDIiwid2FybmluZyI6IiNGMUMwMzcifX0sInNlY3Rpb25zIjoiY2FzaW5vIiwidG9rZW4iOiJleUpyYVdRaU9pSjVOMXBMV0VKbFhDOUhOMlp1Y1ZWamVtTTRNa3BXV2tSWVExSlVObHd2YTI5WVRGUmtXalJJZVhWd2RGRTlJaXdpWVd4bklqb2lVbE15TlRZaWZRLmV5SnpkV0lpT2lJMU1ESmlOalJoWmkwelkySXhMVFF4T0RrdFlUTTBOUzFqWWpGaFkyWmhOakV5TmpFaUxDSnBjM01pT2lKb2RIUndjenBjTDF3dlkyOW5ibWwwYnkxcFpIQXVkWE10WldGemRDMHhMbUZ0WVhwdmJtRjNjeTVqYjIxY0wzVnpMV1ZoYzNRdE1WOHdUM1JFUms0ME56TWlMQ0pwWkdWdWRHbDBlU0k2SW5KdmJHVXViR2x1YTNOOGNtOXNaUzVzYjJkcGJueHliMnhsTG1Ob1lXNW5aVjl3WVhOemQyOXlaSHh5YjJ4bExtUmhjMmhpYjJGeVpIeHliMnhsTG14dloybHVmSEp2YkdVdVkyaGhibWRsWDNCaGMzTjNiM0prZkhKdmJHVXViR2x1YTNNaUxDSmhkWFJvWDNScGJXVWlPakUyTmpZMk5EZzFNVEVzSW01cFkydHVZVzFsSWpvaVVtRmlaSGxPUTB3aUxDSmpkWE4wYjIwNlpHRjBZVjloWTJObGMzTWlPaUp1WTJ3aUxDSmpkWE4wYjIwNllXTmpiM1Z1ZEY5cFpDSTZJaklpTENKbGVIQWlPakUyTmpZMk9URTNNVEVzSW1saGRDSTZNVFkyTmpZME9EVXhNU3dpYW5ScElqb2laVGRoWVRJMk5HSXRNVGM0TkMwME5qbGxMVGsyTlRrdE5UZGlPREF3TXpVeVpEazNJaXdpWlcxaGFXd2lPaUp5WVdKa2VTdHVZMnhBWTJWdWIzSmhMbU52YlNJc0ltTjFjM1J2YlRwMGFYUnNaU0k2SWxKRlVGSkZVMFZPVkVGVVNWWkZJaXdpWTNWemRHOXRPbkp2YkdWeklqb2ljbTlzWlM1c2FXNXJjM3h5YjJ4bExteHZaMmx1ZkhKdmJHVXVZMmhoYm1kbFgzQmhjM04zYjNKa2ZISnZiR1V1WkdGemFHSnZZWEprZkhKdmJHVXViRzluYVc1OGNtOXNaUzVqYUdGdVoyVmZjR0Z6YzNkdmNtUjhjbTlzWlM1c2FXNXJjeUlzSW1WdFlXbHNYM1psY21sbWFXVmtJanAwY25WbExDSmpkWE4wYjIwNllYQndYM0psYzI5MWNtTmxjeUk2SW5KdmJHVXViR2x1YTNNc2NtOXNaUzVzYjJkcGJpeHliMnhsTG1Ob1lXNW5aVjl3WVhOemQyOXlaQ3h5YjJ4bExtUmhjMmhpYjJGeVpDeHliMnhsTG14dloybHVMSEp2YkdVdVkyaGhibWRsWDNCaGMzTjNiM0prTEhKdmJHVXViR2x1YTNNaUxDSndhRzl1WlY5dWRXMWlaWEpmZG1WeWFXWnBaV1FpT25SeWRXVXNJbU52WjI1cGRHODZkWE5sY201aGJXVWlPaUkxTURKaU5qUmhaaTB6WTJJeExUUXhPRGt0WVRNME5TMWpZakZoWTJaaE5qRXlOakVpTENKamRYTjBiMjA2Y0d4MVoybHVjeUk2SWlJc0ltZHBkbVZ1WDI1aGJXVWlPaUpTWVdKa2VTSXNJbU4xYzNSdmJUcG5jbTkxY0hNaU9pSm5jbTkxY0M1allXeHNYMk5sYm5SbGNqMUpSRkJmVGtOTVgweHBkbVZGZUhCbGNtbGxibU5sWDFWelpYSnpMRk5WVUZCUFVsUjhaM0p2ZFhBdVkyOXRjR0Z1ZVQxdVkyd2lMQ0p2Y21sbmFXNWZhblJwSWpvaU5tVTNaVEUzTVRrdE9UWmxOaTAwWXpJNUxUaGlZVEl0TlRKak5UQXhabU15T1Roaklpd2lZM1Z6ZEc5dE9tRmpZMlZ6YzE5eVpYTjBjbWxqZEdsdmJuTWlPaUp5YjJ4bExtRm5aVzUwTG1OaGMybHVieUlzSW1GMVpDSTZJamN5Wm5Sa2NYVTBiVzAxWW5JeFpHNXJaM05zTkhSdWEzSnhJaXdpWlhabGJuUmZhV1FpT2lKbE9EZGpOR05qWWkwd016RmtMVFE1WldJdFlUQXhOUzFtTTJZMk16TTBOR0prTldVaUxDSmpkWE4wYjIwNmFYTmZkSEpoZG1Wc1gyRm5aVzUwSWpvaU1DSXNJblJ2YTJWdVgzVnpaU0k2SW1sa0lpd2libUZ0WlNJNklsSmhZbVI1SWl3aWNHaHZibVZmYm5WdFltVnlJam9pS3pFeE1URXhNVEV4TVRFaUxDSm1ZVzFwYkhsZmJtRnRaU0k2SWtkMWRHbGxjbkpsZWlKOS5QS0YyXzR1alFXaWN0RzUxNER4MUh3azV6RzJyY3Q3TldTWHNrcDdZN1hmUjBETGk3TWRLREh2cE00a2ZJRU1JV3dzbWtBRFdDTFpOWWRLYWdia0pjWEZJQXp1OVl1dnp5QzdVeFpwM2JOcVMtNVpLbHNnVk9vZHZfQ01mNTZZb2U2d1g5ZE9yeEVvakVhdWEtb1MyRzU4MElWX0h1YXVpNG5OUWx3bjlBVnhtVmMyajhqSTJTNXZ1dnppRGdtZHdreWlWNkZHOFRHZDZxcV8ycHVidTg0WWhRclN5bDhVcmNyakJyWDFZZ3VnWWhSdjMybUJWNWhiOWpNUllUbzlnSVV2cFV6VTdfd3pGVWpHY2RQdG9sLTNka2M1RGVGMy1FTXZ4QjRzR0VtYUlITFIzOG5RcDJ1d0FnZWU2VjhKQnV2dEFNa2d0TFo2c2JmdUtFTGpCdkEifQ==']</value>
      <webElementGuid>8590d803-5e52-44da-ae15-e7d7d86f6277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
