<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search</name>
   <tag></tag>
   <elementGuidId>5c0ed619-c63b-4214-b9f9-bd626c4ab11c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_0f3e48a9-c156-4424-9a92-787d58e33c8f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f_0f3e48a9-c156-4424-9a92-787d58e33c8f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1a89285-3d6c-4833-b1b5-2ea88ad36494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a0487c58-dc76-4b1d-b959-4d8b1f5e4501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>8b4874a9-e217-43c4-a508-b9cae683ef40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_0f3e48a9-c156-4424-9a92-787d58e33c8f</value>
      <webElementGuid>463ed0c5-86c6-435c-a323-f629e05b4f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48c4a0fb-f991-493b-916b-735302a4eed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>39109b63-c527-4c49-9a68-659a2f4ebd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_0f3e48a9-c156-4424-9a92-787d58e33c8f&quot;)</value>
      <webElementGuid>484be1c3-c174-4b19-bde4-e12c4490dc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Drap and Drop/Page_NCL Live Experience/iframe_START_extension-iframe</value>
      <webElementGuid>0da68f80-9d73-4d10-adf9-1ffe08522d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_0f3e48a9-c156-4424-9a92-787d58e33c8f']</value>
      <webElementGuid>83ddec9a-90df-43ff-b54d-75e1f2bb7afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/main/div/div[3]/label/div/div/div[2]/input</value>
      <webElementGuid>e2fa5e37-5ea0-443e-9a08-77778f5ceb89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>986a2d7f-c259-4b2e-b9c7-3297fa135f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @id = 'f_0f3e48a9-c156-4424-9a92-787d58e33c8f' and @type = 'text']</value>
      <webElementGuid>03858d6d-3b6f-4aea-908d-61853a5668e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
