<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Staging</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e23c3c0e-93e9-4815-bf50-518ec80b0444</testSuiteGuid>
   <testCaseLink>
      <guid>959d68a0-b0f3-42aa-a9ed-2e83e880d720</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent-Staging/NCLStaging</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>319fc394-2283-4a84-a193-30f3eddb01f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c7d4d0c-3d82-49e0-aecb-1755568b0ea8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6437dbbb-d58e-4b0c-aa79-2ace61bbd07f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f871a27c-510f-4852-ac99-5a8cead11d7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent-Staging/Oceania Staging</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44837b44-9ba8-4296-9f72-afabdf8e706e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7736723-2c8f-4c9f-b4d7-f3c925dcf702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60d03f8e-030e-4790-869a-8e651917a4f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67a530a1-99b4-43f5-a206-9610c5890c3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent-Staging/Regent Staging</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3278b2ae-7cfa-4aae-8dfd-d15ff0c1f465</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e41e06d8-0d1b-450b-80bb-c255113f15af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>454f77d5-7218-4e13-89a5-0d4450e6c0c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88e089f5-d26b-423f-aad5-259da471ca7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent-Staging/Sandals Staging</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f070ef78-acd7-4c36-9619-c0081c795934</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2ac1155-0fd5-48ca-aca1-3dba7021c082</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aecc9896-101d-40cf-8175-8717d0ace729</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
