<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ship_q-carousel__slide q-pa-none</name>
   <tag></tag>
   <elementGuidId>ee032996-fc2e-46c2-8092-236e61a7ea62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.q-carousel__slide.q-pa-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80fbfe55-c9ba-41f1-b36c-62049e8433c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-carousel__slide q-pa-none</value>
      <webElementGuid>40e7400c-3da3-47ec-8f01-6d674b353dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-app&quot;)/div[@class=&quot;full-width full-height column justify-center content-center items-center&quot;]/div[1]/div[@class=&quot;shadow-2-card&quot;]/div[@class=&quot;q-layout-container overflow-hidden&quot;]/div[@class=&quot;absolute-full&quot;]/div[@class=&quot;scroll&quot;]/div[@class=&quot;q-layout q-layout--containerized&quot;]/div[@class=&quot;q-page-container&quot;]/main[@class=&quot;q-page&quot;]/div[1]/div[@class=&quot;text-white q-tab-panels q-panel-parent&quot;]/div[@class=&quot;q-panel scroll&quot;]/div[@class=&quot;q-tab-panel q-px-none q-py-none no-scroll&quot;]/div[1]/div[@class=&quot;column justify-start q-py-none&quot;]/div[1]/div[@id=&quot;card-cruise-ESCAPE7PCVPOPSTTTOVNPIPCV-0&quot;]/div[@class=&quot;q-carousel q-panel-parent q-carousel--without-padding&quot;]/div[@class=&quot;q-carousel__slides-container&quot;]/div[@class=&quot;q-panel scroll&quot;]/div[@class=&quot;q-carousel__slide q-pa-none&quot;]</value>
      <webElementGuid>6168ee4b-deec-4073-8709-2d5859bcd87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder/Page_NCL Live Experience/iframe_Connecting_absolute full-width full-height</value>
      <webElementGuid>0e0362de-9e93-490f-ad53-c0506a2552ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-cruise-ESCAPE7PCVPOPSTTTOVNPIPCV-0']/div/div/div/div</value>
      <webElementGuid>34cdf115-054e-4649-b246-008061da6344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>0be8f2d7-3015-4644-b875-06690cbb9a5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
