<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_north_eastEnter Sectionmore_horiz</name>
   <tag></tag>
   <elementGuidId>cd34a031-acb0-4ad0-9b87-0fe70dbb3ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dcard-action-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div[2]/main/div[2]/div/div[1]/div/div[2]/div/div[1]/div/div/div/div[2]/main/div/div/div/div/div/div/div[1]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9304ca4b-e812-4c88-9e56-30ddc7fda1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcard-action-overlay</value>
      <webElementGuid>e086899b-25de-4bff-9118-2322dbf4a456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>north_eastEnter Sectionmore_horiz</value>
      <webElementGuid>88a58bf1-61dc-4e57-a342-3672ab760e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-app&quot;)/div[@class=&quot;q-layout q-layout--standard&quot;]/div[@class=&quot;q-page-container&quot;]/main[@class=&quot;q-page&quot;]/div[2]/div[1]/div[@class=&quot;full-width&quot;]/div[@class=&quot;q-infinite-scroll&quot;]/div[@class=&quot;row q-px-xl q-py-md q-gutter-x-lg q-gutter-y-lg justify-center bg-grey-3&quot;]/div[@class=&quot;shadow-2-card&quot;]/div[4]/div[1]/div[@class=&quot;dcard-action-overlay&quot;]</value>
      <webElementGuid>340a09be-7a0e-476b-a84f-02e55d45a776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder/Page_NCL Live Experience/iframe_Drop CardHere_extension-iframe</value>
      <webElementGuid>30cf6a2e-b98f-49e6-8ce4-6cb2eb86f555</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/main/div[2]/div/div/div/div[2]/div/div[4]/div/div</value>
      <webElementGuid>2d6ca40e-ddd9-431b-8a4b-36ce44daca79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orlando &amp; Beaches (Port Canaveral)'])[7]/following::div[5]</value>
      <webElementGuid>69a52702-aa69-4049-90d1-b3c4d05b882a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Great Stirrup Cay, Bahamas'])[1]/following::div[5]</value>
      <webElementGuid>98093584-adf2-4f5d-973f-1f8254fc6681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::div[12]</value>
      <webElementGuid>57f316ae-8c2b-487e-947a-a955d8341c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div</value>
      <webElementGuid>9a53eb77-cebb-44f1-b1ce-a1cd59381cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'north_eastEnter Sectionmore_horiz' or . = 'north_eastEnter Sectionmore_horiz')]</value>
      <webElementGuid>0c92bab7-29b6-4b64-ac0c-a47ba5cbcd25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
