<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Drop CardHere_extension-iframe</name>
   <tag></tag>
   <elementGuidId>d692ab0b-2d8d-4b85-beaf-cf770cf4a24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#extension-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='extension-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>56e12d48-3a4a-4d6f-8107-33da3ec73492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>extension-iframe</value>
      <webElementGuid>e5f196c3-a6e7-4bc3-bcc4-685a4d066a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ncl-ext-1.testing.cenora.io?c=eyJjaWQiOiJuY2wiLCJjb25maWciOnsiY29sb3JzIjp7InByaW1hcnkiOiIjMUQxRDFEIiwic2Vjb25kYXJ5IjoiIzAwNzFhNiIsImFjY2VudCI6IiNGRjgzMDkiLCJkYXJrIjoiIzM3MzczNyIsInBvc2l0aXZlIjoiIzIxQkE0NSIsIm5lZ2F0aXZlIjoiI0MxMDAxNSIsImluZm8iOiIjMzFDQ0VDIiwid2FybmluZyI6IiNGMUMwMzcifX0sInNlY3Rpb25zIjoiY2FzaW5vIiwidG9rZW4iOiJleUpyYVdRaU9pSjVOMXBMV0VKbFhDOUhOMlp1Y1ZWamVtTTRNa3BXV2tSWVExSlVObHd2YTI5WVRGUmtXalJJZVhWd2RGRTlJaXdpWVd4bklqb2lVbE15TlRZaWZRLmV5SnpkV0lpT2lJMU1ESmlOalJoWmkwelkySXhMVFF4T0RrdFlUTTBOUzFqWWpGaFkyWmhOakV5TmpFaUxDSnBjM01pT2lKb2RIUndjenBjTDF3dlkyOW5ibWwwYnkxcFpIQXVkWE10WldGemRDMHhMbUZ0WVhwdmJtRjNjeTVqYjIxY0wzVnpMV1ZoYzNRdE1WOHdUM1JFUms0ME56TWlMQ0pwWkdWdWRHbDBlU0k2SW5KdmJHVXViR2x1YTNOOGNtOXNaUzVzYjJkcGJueHliMnhsTG1Ob1lXNW5aVjl3WVhOemQyOXlaSHh5YjJ4bExtUmhjMmhpYjJGeVpIeHliMnhsTG14dloybHVmSEp2YkdVdVkyaGhibWRsWDNCaGMzTjNiM0prZkhKdmJHVXViR2x1YTNNaUxDSmhkWFJvWDNScGJXVWlPakUyTmpjeU16TXdNVFFzSW01cFkydHVZVzFsSWpvaVVtRmlaSGxPUTB3aUxDSmpkWE4wYjIwNlpHRjBZVjloWTJObGMzTWlPaUp1WTJ3aUxDSmpkWE4wYjIwNllXTmpiM1Z1ZEY5cFpDSTZJaklpTENKbGVIQWlPakUyTmpjeU56WXlNVFFzSW1saGRDSTZNVFkyTnpJek16QXhOQ3dpYW5ScElqb2lPVEZtTnpsaE56QXROamt4WVMwME1HSTNMVGcyWWpNdE1UTXpNVGd4WlRabVltUmxJaXdpWlcxaGFXd2lPaUp5WVdKa2VTdHVZMnhBWTJWdWIzSmhMbU52YlNJc0ltTjFjM1J2YlRwMGFYUnNaU0k2SWxKRlVGSkZVMFZPVkVGVVNWWkZJaXdpWTNWemRHOXRPbkp2YkdWeklqb2ljbTlzWlM1c2FXNXJjM3h5YjJ4bExteHZaMmx1ZkhKdmJHVXVZMmhoYm1kbFgzQmhjM04zYjNKa2ZISnZiR1V1WkdGemFHSnZZWEprZkhKdmJHVXViRzluYVc1OGNtOXNaUzVqYUdGdVoyVmZjR0Z6YzNkdmNtUjhjbTlzWlM1c2FXNXJjeUlzSW1WdFlXbHNYM1psY21sbWFXVmtJanAwY25WbExDSmpkWE4wYjIwNllYQndYM0psYzI5MWNtTmxjeUk2SW5KdmJHVXViR2x1YTNNc2NtOXNaUzVzYjJkcGJpeHliMnhsTG1Ob1lXNW5aVjl3WVhOemQyOXlaQ3h5YjJ4bExtUmhjMmhpYjJGeVpDeHliMnhsTG14dloybHVMSEp2YkdVdVkyaGhibWRsWDNCaGMzTjNiM0prTEhKdmJHVXViR2x1YTNNaUxDSndhRzl1WlY5dWRXMWlaWEpmZG1WeWFXWnBaV1FpT25SeWRXVXNJbU52WjI1cGRHODZkWE5sY201aGJXVWlPaUkxTURKaU5qUmhaaTB6WTJJeExUUXhPRGt0WVRNME5TMWpZakZoWTJaaE5qRXlOakVpTENKamRYTjBiMjA2Y0d4MVoybHVjeUk2SWlJc0ltZHBkbVZ1WDI1aGJXVWlPaUpTWVdKa2VTSXNJbU4xYzNSdmJUcG5jbTkxY0hNaU9pSm5jbTkxY0M1allXeHNYMk5sYm5SbGNqMUpSRkJmVGtOTVgweHBkbVZGZUhCbGNtbGxibU5sWDFWelpYSnpMRk5WVUZCUFVsUjhaM0p2ZFhBdVkyOXRjR0Z1ZVQxdVkyd2lMQ0p2Y21sbmFXNWZhblJwSWpvaU5qUXpOall5TXpjdFpXUmxaUzAwWVRObExXSXpaV1V0TVRCa016TXlPREF3Tm1Waklpd2lZM1Z6ZEc5dE9tRmpZMlZ6YzE5eVpYTjBjbWxqZEdsdmJuTWlPaUp5YjJ4bExtRm5aVzUwTG1OaGMybHVieUlzSW1GMVpDSTZJamN5Wm5Sa2NYVTBiVzAxWW5JeFpHNXJaM05zTkhSdWEzSnhJaXdpWlhabGJuUmZhV1FpT2lKbE16Y3dZamRsWXkxa05qaGtMVFJrWlRJdFlUazFaaTB4TXpZeE1tUXdaV1l6T1RraUxDSmpkWE4wYjIwNmFYTmZkSEpoZG1Wc1gyRm5aVzUwSWpvaU1DSXNJblJ2YTJWdVgzVnpaU0k2SW1sa0lpd2libUZ0WlNJNklsSmhZbVI1SWl3aWNHaHZibVZmYm5WdFltVnlJam9pS3pFeE1URXhNVEV4TVRFaUxDSm1ZVzFwYkhsZmJtRnRaU0k2SWtkMWRHbGxjbkpsZWlKOS5KMW9EUnZNaGhwNl9PNG4waGpyZXg5V2NZYjhSQ0gzLVREYnBzSHVpaTRJcVM4dTRvcmVmdy00Sy1ncHF2ckdfN2wtVy1LWktIQm4tRmhlb0pibkZaX3JfNHhFdlFHZnJybEpOMkNCa0RJNW44U21mSy1yanpHdjAzSzdJTzMxbm5CWEdDM1FEZmY5YlUxNmFNbVdaRENRRHl2bktKZUQ3YnBfeU5KSi1IQTh5aThJd1h3Vk9LeWJyQ01Ic180MlRNQlpFaXhSMjFvVGhCcmZNSm5BaDZVSFZaSGJQeExCdjJkVzhrVnRySXZheFk3QzRab2E5MWlFbkhsa1hyaHJuLV9hcUxsWUhIV0RaYjZvdEtvZUQ2NFlTamh2WE1ZUjc5V05Ea3BNMVpsRXRPYU1ObDRjOWdGMnhtUjlaaFgyR1ZmQVVCSkY1MWIzTklZcmJCNm5UUFEifQ==</value>
      <webElementGuid>6f7afc22-3894-48fc-a08d-a2dc1395775a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>98091a3e-c7b9-435b-acd4-b365f4a9a708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>aba28d1b-e151-4341-af60-3099acbed918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;extension-iframe&quot;)</value>
      <webElementGuid>214d3387-d8cd-4d35-9027-21e66b06ca3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='extension-iframe']</value>
      <webElementGuid>b711ce7f-c428-451a-9f85-44fb38621524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[3]/div/div/div/div/div/div/main/div/iframe</value>
      <webElementGuid>987ffc13-9aa7-4edd-b79d-b1b7334676ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/iframe</value>
      <webElementGuid>d371c143-21d2-491b-ab42-74ee4a175e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'extension-iframe' and @src = 'https://ncl-ext-1.testing.cenora.io?c=eyJjaWQiOiJuY2wiLCJjb25maWciOnsiY29sb3JzIjp7InByaW1hcnkiOiIjMUQxRDFEIiwic2Vjb25kYXJ5IjoiIzAwNzFhNiIsImFjY2VudCI6IiNGRjgzMDkiLCJkYXJrIjoiIzM3MzczNyIsInBvc2l0aXZlIjoiIzIxQkE0NSIsIm5lZ2F0aXZlIjoiI0MxMDAxNSIsImluZm8iOiIjMzFDQ0VDIiwid2FybmluZyI6IiNGMUMwMzcifX0sInNlY3Rpb25zIjoiY2FzaW5vIiwidG9rZW4iOiJleUpyYVdRaU9pSjVOMXBMV0VKbFhDOUhOMlp1Y1ZWamVtTTRNa3BXV2tSWVExSlVObHd2YTI5WVRGUmtXalJJZVhWd2RGRTlJaXdpWVd4bklqb2lVbE15TlRZaWZRLmV5SnpkV0lpT2lJMU1ESmlOalJoWmkwelkySXhMVFF4T0RrdFlUTTBOUzFqWWpGaFkyWmhOakV5TmpFaUxDSnBjM01pT2lKb2RIUndjenBjTDF3dlkyOW5ibWwwYnkxcFpIQXVkWE10WldGemRDMHhMbUZ0WVhwdmJtRjNjeTVqYjIxY0wzVnpMV1ZoYzNRdE1WOHdUM1JFUms0ME56TWlMQ0pwWkdWdWRHbDBlU0k2SW5KdmJHVXViR2x1YTNOOGNtOXNaUzVzYjJkcGJueHliMnhsTG1Ob1lXNW5aVjl3WVhOemQyOXlaSHh5YjJ4bExtUmhjMmhpYjJGeVpIeHliMnhsTG14dloybHVmSEp2YkdVdVkyaGhibWRsWDNCaGMzTjNiM0prZkhKdmJHVXViR2x1YTNNaUxDSmhkWFJvWDNScGJXVWlPakUyTmpjeU16TXdNVFFzSW01cFkydHVZVzFsSWpvaVVtRmlaSGxPUTB3aUxDSmpkWE4wYjIwNlpHRjBZVjloWTJObGMzTWlPaUp1WTJ3aUxDSmpkWE4wYjIwNllXTmpiM1Z1ZEY5cFpDSTZJaklpTENKbGVIQWlPakUyTmpjeU56WXlNVFFzSW1saGRDSTZNVFkyTnpJek16QXhOQ3dpYW5ScElqb2lPVEZtTnpsaE56QXROamt4WVMwME1HSTNMVGcyWWpNdE1UTXpNVGd4WlRabVltUmxJaXdpWlcxaGFXd2lPaUp5WVdKa2VTdHVZMnhBWTJWdWIzSmhMbU52YlNJc0ltTjFjM1J2YlRwMGFYUnNaU0k2SWxKRlVGSkZVMFZPVkVGVVNWWkZJaXdpWTNWemRHOXRPbkp2YkdWeklqb2ljbTlzWlM1c2FXNXJjM3h5YjJ4bExteHZaMmx1ZkhKdmJHVXVZMmhoYm1kbFgzQmhjM04zYjNKa2ZISnZiR1V1WkdGemFHSnZZWEprZkhKdmJHVXViRzluYVc1OGNtOXNaUzVqYUdGdVoyVmZjR0Z6YzNkdmNtUjhjbTlzWlM1c2FXNXJjeUlzSW1WdFlXbHNYM1psY21sbWFXVmtJanAwY25WbExDSmpkWE4wYjIwNllYQndYM0psYzI5MWNtTmxjeUk2SW5KdmJHVXViR2x1YTNNc2NtOXNaUzVzYjJkcGJpeHliMnhsTG1Ob1lXNW5aVjl3WVhOemQyOXlaQ3h5YjJ4bExtUmhjMmhpYjJGeVpDeHliMnhsTG14dloybHVMSEp2YkdVdVkyaGhibWRsWDNCaGMzTjNiM0prTEhKdmJHVXViR2x1YTNNaUxDSndhRzl1WlY5dWRXMWlaWEpmZG1WeWFXWnBaV1FpT25SeWRXVXNJbU52WjI1cGRHODZkWE5sY201aGJXVWlPaUkxTURKaU5qUmhaaTB6WTJJeExUUXhPRGt0WVRNME5TMWpZakZoWTJaaE5qRXlOakVpTENKamRYTjBiMjA2Y0d4MVoybHVjeUk2SWlJc0ltZHBkbVZ1WDI1aGJXVWlPaUpTWVdKa2VTSXNJbU4xYzNSdmJUcG5jbTkxY0hNaU9pSm5jbTkxY0M1allXeHNYMk5sYm5SbGNqMUpSRkJmVGtOTVgweHBkbVZGZUhCbGNtbGxibU5sWDFWelpYSnpMRk5WVUZCUFVsUjhaM0p2ZFhBdVkyOXRjR0Z1ZVQxdVkyd2lMQ0p2Y21sbmFXNWZhblJwSWpvaU5qUXpOall5TXpjdFpXUmxaUzAwWVRObExXSXpaV1V0TVRCa016TXlPREF3Tm1Waklpd2lZM1Z6ZEc5dE9tRmpZMlZ6YzE5eVpYTjBjbWxqZEdsdmJuTWlPaUp5YjJ4bExtRm5aVzUwTG1OaGMybHVieUlzSW1GMVpDSTZJamN5Wm5Sa2NYVTBiVzAxWW5JeFpHNXJaM05zTkhSdWEzSnhJaXdpWlhabGJuUmZhV1FpT2lKbE16Y3dZamRsWXkxa05qaGtMVFJrWlRJdFlUazFaaTB4TXpZeE1tUXdaV1l6T1RraUxDSmpkWE4wYjIwNmFYTmZkSEpoZG1Wc1gyRm5aVzUwSWpvaU1DSXNJblJ2YTJWdVgzVnpaU0k2SW1sa0lpd2libUZ0WlNJNklsSmhZbVI1SWl3aWNHaHZibVZmYm5WdFltVnlJam9pS3pFeE1URXhNVEV4TVRFaUxDSm1ZVzFwYkhsZmJtRnRaU0k2SWtkMWRHbGxjbkpsZWlKOS5KMW9EUnZNaGhwNl9PNG4waGpyZXg5V2NZYjhSQ0gzLVREYnBzSHVpaTRJcVM4dTRvcmVmdy00Sy1ncHF2ckdfN2wtVy1LWktIQm4tRmhlb0pibkZaX3JfNHhFdlFHZnJybEpOMkNCa0RJNW44U21mSy1yanpHdjAzSzdJTzMxbm5CWEdDM1FEZmY5YlUxNmFNbVdaRENRRHl2bktKZUQ3YnBfeU5KSi1IQTh5aThJd1h3Vk9LeWJyQ01Ic180MlRNQlpFaXhSMjFvVGhCcmZNSm5BaDZVSFZaSGJQeExCdjJkVzhrVnRySXZheFk3QzRab2E5MWlFbkhsa1hyaHJuLV9hcUxsWUhIV0RaYjZvdEtvZUQ2NFlTamh2WE1ZUjc5V05Ea3BNMVpsRXRPYU1ObDRjOWdGMnhtUjlaaFgyR1ZmQVVCSkY1MWIzTklZcmJCNm5UUFEifQ==']</value>
      <webElementGuid>fd24bd62-0feb-40d2-b720-c43b9292951b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
