<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Card_origen - Copy</name>
   <tag></tag>
   <elementGuidId>56d58ce7-b3dd-4933-b75f-61e0620ee0b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.q-img__content.absolute-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id,&quot;card-cruise&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2987b965-6791-45b8-89ae-e7ebfe2b1b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-img__content absolute-full</value>
      <webElementGuid>35520290-4e51-4a35-a5cb-a8b6376faefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-app&quot;)/div[@class=&quot;full-width column justify-center items-center auth-bg&quot;]/div[@class=&quot;q-py-xl bg-white column justify-center items-center content-center login-box-shadown&quot;]/div[1]/div[@class=&quot;q-img overflow-hidden&quot;]/div[@class=&quot;q-img__content absolute-full&quot;]</value>
      <webElementGuid>a5f903b4-f830-433e-b823-c414ae568401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Flujo Completo/Page_NCL Live Experience/iframe_Search</value>
      <webElementGuid>5bbdd7a8-b85a-44f6-b145-0f86d58cbfbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/div/div/div[3]</value>
      <webElementGuid>8504c418-42ea-4e9d-a7f4-f25e3841cbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>ff0ffc57-c71e-49e9-b854-70047a68e1b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
