<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Card_origen</name>
   <tag></tag>
   <elementGuidId>b84a4855-a85a-4ca9-9337-1fdaa77b1ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.q-img__content.absolute-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//div[@class='q-carousel__slide q-pa-none']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58139970-6f65-411c-bff2-68922037cee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-img__content absolute-full</value>
      <webElementGuid>e9cbb4a0-fcdf-48c4-92c4-02fa07b8e830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-app&quot;)/div[@class=&quot;full-width column justify-center items-center auth-bg&quot;]/div[@class=&quot;q-py-xl bg-white column justify-center items-center content-center login-box-shadown&quot;]/div[1]/div[@class=&quot;q-img overflow-hidden&quot;]/div[@class=&quot;q-img__content absolute-full&quot;]</value>
      <webElementGuid>8df1f697-f753-4129-ba4a-2645977d9994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Flujo Completo/Page_NCL Live Experience/iframe_Search</value>
      <webElementGuid>24b83a6d-01e6-4cf9-b4d9-2681ce4350c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/div/div/div[3]</value>
      <webElementGuid>28660048-2374-4620-a93d-889363873d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>d4a6222d-2696-430b-8f39-a72bab791f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
