<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>96ab354c-99e1-4408-8c66-e74158f8f241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@aria-label,'Email')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56b8d4fe-1855-4fc5-aeab-e4e9e3921a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99e836c3-98e6-45cd-b98f-76a437cfce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>70710653-234c-4a33-844b-820ca921cbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>5bcdb0b8-702e-4875-85e8-f86d15cd091f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>ed086bc9-2b18-4a37-bdbf-8166fa5f9daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f</value>
      <webElementGuid>69839b8b-1129-4ce2-8c76-bad70e00159e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84dc6d3f-5965-452d-bfcf-38467741e343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>496e7041-a2d5-4788-9189-7b0102135f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f&quot;)</value>
      <webElementGuid>aa482bb2-14e1-4c1b-819a-52550eb69b70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f']</value>
      <webElementGuid>6020851c-1138-448e-9dff-5da100f40ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/form/div/label/div/div/div[2]/input</value>
      <webElementGuid>6f44eb4b-020a-4c85-bf95-56bcde186f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d00481be-19e9-45bf-842e-6222cadc761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f' and @type = 'text']</value>
      <webElementGuid>1a493e20-837c-43f4-bca0-d5239ad0051c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
