<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code</name>
   <tag></tag>
   <elementGuidId>fdf3cee6-5129-4795-a2ad-79ce4fb4bbd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c3453c6-16ff-4d54-b794-b35edfa829d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>932bdcaa-bd66-4aa7-9c9f-1d3683de79ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Code</value>
      <webElementGuid>79f67bd5-76e9-4a6d-a173-a3a89f178f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f</value>
      <webElementGuid>03f57199-d651-4aa0-89d7-fd824db6aae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f45a081-4ab5-46bb-83b1-4e436de8cb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>f2c49067-a255-46c0-a4eb-afcbb707a2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f&quot;)</value>
      <webElementGuid>ee7837fd-7142-4c8d-b9b7-a9de0aa59c37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f']</value>
      <webElementGuid>dae2303b-dc9a-4f59-9f4b-387ec051ef34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[2]/div[2]/div/div/label/div/div/div[2]/input</value>
      <webElementGuid>cea4b16c-9baf-40ec-8b0b-f8cf7d9cf352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>264fdb90-08d0-4866-901f-41e896259038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Code' and @id = 'f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f' and @type = 'text']</value>
      <webElementGuid>037d0ad3-ba24-4459-b422-3fd4a4d1c26a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
