<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer</name>
   <tag></tag>
   <elementGuidId>9fa7cba7-31e0-42b6-a0c6-a1f37fa932ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e8ea965-b325-4194-8506-3aa502f66a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>42f47130-618a-4a0f-9a59-32eb55103be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf0c53ba-8c78-41b8-b20d-5ed76bdf6e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>a929c364-644d-414e-a716-2698bd5355b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>e53a1df1-2ee6-4888-9de9-71248011ed40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b89252ae-ddaa-4d8f-8fdb-b48c7d6b2338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>6890da94-2d12-42c3-9ff6-92a13fb6b7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>01fac15a-4ab7-4836-928f-9a80667c3977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      <webElementGuid>503f5b23-05ca-47d6-abeb-8bf7316d9c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__input q-placeholder col q-field__input--padding</value>
      <webElementGuid>f24bdc41-5347-4693-95a2-27f8bcdf4c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_a6ee8b0a-7dde-4558-a4d5-92035df88206&quot;)</value>
      <webElementGuid>687c883e-f32a-4cba-86f6-5eee645f131a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>fcc30c34-1517-4972-817e-19a64140f6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[2]/div[2]/div/div/div/label/div/div/div[2]/div/input</value>
      <webElementGuid>4c32303c-4701-4326-8c5d-7a440f27f53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>094fd98e-48bf-4baa-be2e-22828fc44f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>5e653885-234c-491d-899b-a14b3789e6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
