<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_password</name>
   <tag></tag>
   <elementGuidId>53959ff6-eba6-4f8d-8e85-0e0ffc5df00f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_75c0b9dc-bd11-4026-9c02-df339169eaee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'password')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aac8d3b0-f27d-41ad-bb57-dd49c95fc411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>969da37d-0271-4078-abd5-d81c80c507d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>d45555be-941c-45dc-b791-4856475d6055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c095bc18-a296-40ca-8fa6-17bebe0e0790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>46bcbe71-0291-46c0-85b3-c2b3bd19e274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_75c0b9dc-bd11-4026-9c02-df339169eaee</value>
      <webElementGuid>55439171-7ebb-4ac9-b0bf-9589389710d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ef7665a5-2b29-4b15-8e71-97f2c405ce75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>32a1fc59-12de-4b0c-afa1-a7baa76b2ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_75c0b9dc-bd11-4026-9c02-df339169eaee&quot;)</value>
      <webElementGuid>fdc3d632-d0a9-422d-a783-740eac7d7c5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_75c0b9dc-bd11-4026-9c02-df339169eaee']</value>
      <webElementGuid>951527b4-fc9e-419f-9d19-212d27e786f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/form/div[2]/label/div/div/div[2]/input</value>
      <webElementGuid>9fd603fa-f5c7-4880-8b6c-1f6f12271622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div/div/div[2]/input</value>
      <webElementGuid>21057131-a5d1-4d65-bb0f-a69d028fc988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @id = 'f_75c0b9dc-bd11-4026-9c02-df339169eaee' and @type = 'password']</value>
      <webElementGuid>e10f9447-0c08-48a7-b76c-abf9563b2c0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
