<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Option_EnabledPointer</name>
   <tag></tag>
   <elementGuidId>a1485c96-e385-4a72-9ac6-fe098cdb400a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.q-img__content.absolute-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//i[@role='img'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5f1e225-0de5-4155-8435-e8ab975b9a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-img__content absolute-full</value>
      <webElementGuid>418e155b-0220-4aca-9918-311ea2d2a4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-app&quot;)/div[@class=&quot;full-width column justify-center items-center auth-bg&quot;]/div[@class=&quot;q-py-xl bg-white column justify-center items-center content-center login-box-shadown&quot;]/div[1]/div[@class=&quot;q-img overflow-hidden&quot;]/div[@class=&quot;q-img__content absolute-full&quot;]</value>
      <webElementGuid>f2bcd026-818f-44b3-b513-e04f372fc401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/div/div/div[3]</value>
      <webElementGuid>df622618-6f5c-4b75-8572-a2ea41846746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>51c32dc9-7049-43b4-9022-b63d58d9cd9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
