<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ending Session</name>
   <tag></tag>
   <elementGuidId>56a42872-0bd4-49d8-9cc9-4e37a1d8fdbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[3]/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f27c1fc-a7e4-4c82-9279-6d079eddc666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>cf4a4074-308c-48f4-8909-f0d8a443c80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ending Session</value>
      <webElementGuid>6a68af27-fa1d-41e3-b283-680c294ddec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-app&quot;)/div[@class=&quot;q-layout q-layout--standard&quot;]/div[@class=&quot;q-drawer-container&quot;]/aside[@class=&quot;q-drawer q-drawer--right q-drawer--standard fixed&quot;]/div[@class=&quot;q-drawer__content fit scroll&quot;]/div[1]/div[@class=&quot;q-tab-panels q-panel-parent&quot;]/div[@class=&quot;q-panel scroll&quot;]/div[@class=&quot;q-tab-panel q-pa-none&quot;]/div[1]/div[@class=&quot;column justify-evenly items-center content-center overflow-hidden bg-white&quot;]/div[@class=&quot;bg-white&quot;]/div[@class=&quot;overlay row items-center justify-center text-center&quot;]/div[@class=&quot;col-12 text-white&quot;]/div[@class=&quot;message&quot;]</value>
      <webElementGuid>7b4b0fc3-ddcf-4bf0-b4f5-5e754efedfd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[3]/div/div[2]/div[2]/div</value>
      <webElementGuid>84feadc8-1aa2-4865-b131-c2c71eb5c7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connecting...'])[1]/following::div[7]</value>
      <webElementGuid>b165714b-ff6d-4d33-84f6-985e42b13418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose an extra-functionality'])[1]/preceding::div[21]</value>
      <webElementGuid>db57ad26-f1fb-460f-9a80-1cf28b95f874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecting an icon from this panel’s toolbar'])[1]/preceding::div[21]</value>
      <webElementGuid>f35cb006-5015-4a37-8cc7-d39c9d7bf37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ending Session']/parent::*</value>
      <webElementGuid>1fe6ea84-aa2e-4a4d-9614-9af755ecbdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>bd69841c-0b41-46ef-b358-2febdeba1efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ending Session' or . = 'Ending Session')]</value>
      <webElementGuid>18f50a91-a8d6-4228-b356-09f9b86fd289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
