<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code</name>
   <tag></tag>
   <elementGuidId>afc492ee-358d-4cc0-9ff3-a16e17197338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96a331c5-6aa3-4a2f-8e23-e81020cb84ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>df380c59-2781-4626-a190-bc8f899bfc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Code</value>
      <webElementGuid>95be1a01-9e31-488d-ab9e-4786f1569c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f</value>
      <webElementGuid>82856689-e78e-41b5-911a-80a139bff096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bac5e3f6-499d-4996-be49-5f5dd2c74168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>4133ad6e-bb71-4c7a-b9e0-322e0b6cddb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f&quot;)</value>
      <webElementGuid>50865171-b5e9-4913-b3cf-f6baa204679d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f']</value>
      <webElementGuid>dc194550-d8e2-442e-b679-7a051cad3260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[2]/div[2]/div/div/label/div/div/div[2]/input</value>
      <webElementGuid>c7067104-a775-4cea-a177-93f48b634f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0dd3d0b8-282f-43ec-a069-4f9034f558b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Code' and @id = 'f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f' and @type = 'text']</value>
      <webElementGuid>815a94f0-5bcb-4e16-9fe3-3f2a87b3b999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
