<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer</name>
   <tag></tag>
   <elementGuidId>e3d5ad63-b2ac-45d2-a4fc-8b242ed1d2a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5aa6ffb-5147-457d-be91-09fc0ab72269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6d7e0c16-71b3-45c4-a1e7-cdc6bea54b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d24aa59e-dbd3-4953-b84b-776a854466c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3157e0e2-ab9c-4c9f-8d7a-1ae938240ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>8b504ce5-3616-4b07-b275-1b2e0c2eb4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>751172fd-d9b6-4a77-9ef8-7a95ea5d8d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>9f0dbb3e-f215-4831-b878-9e490b0cf31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>b7f3720e-787a-4a9f-a260-2cf94d4bf9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      <webElementGuid>388383b7-688a-4388-ba84-7f8aadf791a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__input q-placeholder col q-field__input--padding</value>
      <webElementGuid>9cac7a58-5222-4f21-9fdb-f5bb854ce6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_a6ee8b0a-7dde-4558-a4d5-92035df88206&quot;)</value>
      <webElementGuid>62c32dd6-1e76-4163-8aaa-e76ad5945e72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>b1dfb790-95c9-46a7-80f6-19832578025a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[2]/div[2]/div/div/div/label/div/div/div[2]/div/input</value>
      <webElementGuid>6bcb5194-d5cc-440c-9101-8afc9bb8edc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>429de66d-78e6-477d-b371-7bc6a3aa2699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>a5e6b7cc-4748-4057-b2b0-4ce313b2d4f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
