<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Message_Agent</name>
   <tag></tag>
   <elementGuidId>2a00bcc0-7ea0-4e17-926e-c0892ed41140</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.access-code-box > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;q-app&quot;]/div[1]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8e6077ff-b134-4cb0-b1a7-86c31a6b6050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5443</value>
      <webElementGuid>d6123ab7-ca2e-45ee-bfe0-d503f7a125a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-app&quot;)/div[@class=&quot;full-width&quot;]/div[@class=&quot;full-height column q-px-lg q-py-xl content-center items-center justify-between bg-gradient text-white&quot;]/div[3]/div[@class=&quot;access-code-box&quot;]/span[1]</value>
      <webElementGuid>11317f8b-2d5e-4550-b4ef-7308075ecab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Sesion for Code/Page_NCL/iframe</value>
      <webElementGuid>d1a58155-88dc-41af-909d-5f130c8049d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/div[3]/div/span</value>
      <webElementGuid>01b48898-ea34-46c3-be61-c7ef4e49a25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please pass the following code to our sales agent'])[1]/following::span[1]</value>
      <webElementGuid>2c2bd5cc-c578-4e81-996d-407ac5e93db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy.'])[1]/preceding::span[1]</value>
      <webElementGuid>ec243e2d-97cb-423d-bfe5-7db8e0d9f130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Oops...Something didn', &quot;'&quot;, 't work as expected.')])[1]/preceding::span[1]</value>
      <webElementGuid>7124839a-2ff0-4f30-b86a-6c48a0897ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5443']/parent::*</value>
      <webElementGuid>ac49dca8-2bec-4b32-80ac-26fc08de9a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>adfef388-b8d5-4c4e-9518-7afbfd579d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '5443' or . = '5443')]</value>
      <webElementGuid>9db8d4a9-b69a-42d4-9e80-160deed20401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
