<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ByActivity_Golf</name>
   <tag></tag>
   <elementGuidId>ec7b3d95-a613-4868-9e42-49a180f22873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[2]/div[1]/div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b14a4b7e-c6fe-4dbd-9e1b-07973468ced5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>4108a644-37a7-44b9-b180-92fa9dce9a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f069130d-f90c-4af9-9b4a-0991ec065744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>d3732ba9-d746-4650-a4dc-a08d5690614c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>11de78ed-573a-49ec-bd8c-0a917e41b7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3061b9b-57c4-458f-8852-aea4d4a1bdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>cbd7d1f5-f07a-4dc8-95e5-5482468d7303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>e5b9b8b7-0a85-4e50-b4af-5f773fe5240e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      <webElementGuid>ab939d56-14d1-4ed0-94ec-1fff9d2321fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__input q-placeholder col q-field__input--padding</value>
      <webElementGuid>9016cbce-a35e-4688-be18-9ee6353b5977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_a6ee8b0a-7dde-4558-a4d5-92035df88206&quot;)</value>
      <webElementGuid>c2d508ab-aae9-4452-8d51-5c04d0102396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Agent/IframeAgent</value>
      <webElementGuid>165c915d-d24d-4e6d-b346-12e04cebb063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>103c010f-14d7-4b7a-84bd-b32f6be3bdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[2]/div[2]/div/div/div/label/div/div/div[2]/div/input</value>
      <webElementGuid>e3f46a43-ce05-4401-a95a-de7882ef64c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f8d17fd9-1cb9-411b-9c6b-da3cdd461fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>c2190274-4599-40a1-9121-1efb92bc73cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
