<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_droppable</name>
   <tag></tag>
   <elementGuidId>6100adf2-cb4d-4ac7-af70-cfe15494aaf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.access-code-box > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(.,'Drop here')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dad9aeff-5a37-4294-80f2-010734f3b957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5443</value>
      <webElementGuid>75c406eb-e5ba-4af6-ad6d-236329545eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-app&quot;)/div[@class=&quot;full-width&quot;]/div[@class=&quot;full-height column q-px-lg q-py-xl content-center items-center justify-between bg-gradient text-white&quot;]/div[3]/div[@class=&quot;access-code-box&quot;]/span[1]</value>
      <webElementGuid>55de9af3-9ea4-47cc-af46-dd7d0025c284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/div[3]/div/span</value>
      <webElementGuid>d7b88c26-177a-48f5-ba6c-ca9bb063989c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
