<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_draggable</name>
   <tag></tag>
   <elementGuidId>90ac2fb8-a960-45b0-ba65-fef8d6beaff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.access-code-box > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[contains(.,'Drag me to my target')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b0b94bc-0943-4931-8255-06c1c9d44d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5443</value>
      <webElementGuid>7e2bcc69-695d-4476-89d3-330f3f93bf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-app&quot;)/div[@class=&quot;full-width&quot;]/div[@class=&quot;full-height column q-px-lg q-py-xl content-center items-center justify-between bg-gradient text-white&quot;]/div[3]/div[@class=&quot;access-code-box&quot;]/span[1]</value>
      <webElementGuid>8445ad65-9384-40bf-8115-b220b47c0d0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/div[3]/div/span</value>
      <webElementGuid>6b3b253e-2062-406c-9c45-32fb2da0c027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
