<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer</name>
   <tag></tag>
   <elementGuidId>00ec8a32-2aed-46d7-974a-4e82f172cc11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>588012cb-d0ca-4978-a2ad-ec0418f4d898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b8775fbb-4154-4190-8f22-fa91818fd900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>52b82623-5de2-412e-8fc1-7c1d704128fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f5c15ecc-e80f-4d39-8904-4997e9d9d4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>4e2b4157-0e2f-4b87-aaa2-1aee692d3dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af747f04-c8ff-4a15-baff-5f6a72035039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>c38eb97a-3f21-469e-99fe-ee8ee678991e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206_lb</value>
      <webElementGuid>b6786bae-8cc7-45db-bb20-bf3326b26b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_a6ee8b0a-7dde-4558-a4d5-92035df88206</value>
      <webElementGuid>987ee6e8-fdf2-4a82-b92e-49666df724ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__input q-placeholder col q-field__input--padding</value>
      <webElementGuid>71812118-3529-4027-a0b1-54ed25e3273d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_a6ee8b0a-7dde-4558-a4d5-92035df88206&quot;)</value>
      <webElementGuid>2993b6e3-c968-4e7d-8125-7fd9c8ddd17a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>59e9b1a8-26a0-4a3c-8ad1-e9f2416e7154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[2]/div[2]/div/div/div/label/div/div/div[2]/div/input</value>
      <webElementGuid>45d17539-b869-47dd-8692-4bb73c646320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5c15434a-ef45-44f2-afa0-4bd58d5c481e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'f_a6ee8b0a-7dde-4558-a4d5-92035df88206']</value>
      <webElementGuid>26bfed15-0429-473e-82f5-9484e2964b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
