<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code</name>
   <tag></tag>
   <elementGuidId>6cae303f-11cc-47a3-9379-b9b11bc090a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00c44230-79cb-4385-b796-03031294ca3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>383f9556-ad57-4b56-8589-12c1a1a2ee1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Code</value>
      <webElementGuid>c41fff72-8133-430d-8407-a40486e96f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f</value>
      <webElementGuid>9e38125b-6099-4199-baa7-163afd71e6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48935019-e263-44f2-8b45-eae734171e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>35b6e675-3ff6-4485-a684-8f7906063199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f&quot;)</value>
      <webElementGuid>26531217-a61f-4463-9b27-eb61a8ca51f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f']</value>
      <webElementGuid>25f349b2-03cf-4c91-a958-a03575e1cf5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div[2]/aside/div/div/div/div/div/div/div[2]/div[2]/div/div/label/div/div/div[2]/input</value>
      <webElementGuid>369858a6-5d54-43c1-b9a4-8d1839866242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f669aeb4-a76c-416d-a479-6c1e401b8e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Code' and @id = 'f_49bd250c-b34e-4b3c-9fdb-b16ca511d98f' and @type = 'text']</value>
      <webElementGuid>53c114e0-305e-425f-ac76-ac854e1bfeae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
