<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>90860590-94dc-4c36-9f56-6b9fef141ade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@aria-label,'Email')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fe87260-9941-41e3-bab7-976a9da0e52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>289137d5-767d-4673-9084-212e20ffaab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>6e852422-c068-481c-bda6-99f3324dc9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>58408a4e-1bd2-49c8-99a8-1b8d26c62f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8141b73f-70d9-480c-9e73-127b77b197e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f</value>
      <webElementGuid>1c3c0a8f-d708-47f3-889d-76dd8f3b1e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9c2bb35-8ed8-4f9d-85b8-bc1788b290e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>29742eac-af16-469d-97c0-f3da80cc9483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f&quot;)</value>
      <webElementGuid>0944c18b-5a00-4de2-9038-869f2ba676a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f']</value>
      <webElementGuid>eed45a4e-f78c-4d01-a5fd-5ea2d20ad85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/form/div/label/div/div/div[2]/input</value>
      <webElementGuid>734b4b37-b9bb-4c27-bc33-17afc926565b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>348f78b4-70a4-474f-ad9c-2fd0dcac6ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'f_27b13053-4bd3-4a20-a7e3-4abf3c38af0f' and @type = 'text']</value>
      <webElementGuid>f52ffcd6-381b-4abf-9c27-5aa48f5ec0fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
